services:
  ocr-api:
    container_name: nemotron_ocr_api
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./:/app
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]